- name: Download Graylog Package
  get_url: url={{ graylog_package_url }} dest={{ graylog_package_dest }}
  when: graylog_download_package == "yes"


- name: Copy Graylog Package
  copy: src=//srv/files/collector-sidecar-0.1.0-1.x86_64.rpm dest={{graylog_package_local}}
  when: graylog_download_package == "no"

        
- name: Install Graylog Package
  yum:  name="{{graylog_package_local}}" state=present