- include: install-redhat.yml
  tags: graylog 

- name: Check if Graylog Service Exists
  stat: path=/etc/systemd/system/collector-sidecar.service
  register: service_status
  tags: graylog

- name: Install graylog sidecar service
  command: "graylog-collector-sidecar -service install"
  when: service_status.stat.exists == False
  tags: graylog

- name: Copy graylog config 
  template: src=collector_sidecar.j2 dest=/etc/graylog/collector-sidecar/collector_sidecar.yml
  notify: restart_graylog
  tags: graylog

- name: Start Service
  service: name=collector-sidecar state=started enabled=yes
  tags: graylog
